baseURL = "https://sguzman.github.io/marginalia/"
languageCode = "en-us"
title = "Marginalia"
theme = "coder"

[params]
avatarURL = "images/avatar.png"
customCSS = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
